Update test to use `String.prototype.slice()` over `.substr()`
exercism/typescript pull request #1417
Opened 2024-01-19 22:01 UTC by Ak5cel

`String.prototype.substr()` was deprecated, so the test is refactored to use `String.prototype.slice()` instead

(Fixes #1416, it was auto-closed earlier)

2024-02-02 18:00 UTC, SleeplessByte requested changes
Please remove the unrelated formatting changes.

The replacement for `substr` is [`substring`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring), not `slice`, despite both being _almost_ the same.

2024-02-04 16:04 UTC, Ak5cel commented
Ahh gotcha, making the changes now

2024-02-04 16:26 UTC, Ak5cel commented
Dropped the previous commits so it's now a clean one with just the refactor.

(Syncing my fork on GitHub made that last commit, can remove it if needed)

2024-02-04 18:49 UTC, Ak5cel commented
👍 

Cleaned it up so it's now 1 commit rebased to after the latest commits on main

2024-02-04 20:14 UTC, SleeplessByte approved these changes

2024-02-04 20:15 UTC, merged

2024-02-04 20:15 UTC, SleeplessByte commented
Thanks!